### ISSUE TITLE
Wifi Provisioning failed with code 500

### ISSUE THREAD

**Issue by IeP4nieF** [Hypfer/valetudo-companion#14]
valetudo-companion finds my fresh flashed Roborock S5 ("Found unprovisioned robot: Roborock S5"). But after I filled in SSID and Password from the wifi the S5 should use, I always get the message "Wifi Provisioning failed with code 500" after tipping on "CONNECT" and nothing happens.

I'm using valetudo-companion 2022.03.0 from f-droid.org.

Is there a possibility to debug this issue?

**Comment by raphaelmaenle** [comment]
For anyone dropping in; I thought I had the same issue but it turned out that the robot hadn't fully finished startup. There was 1-2 minutes of time where the Wifi of the robot was available, but the robot wasn't yet actually able to respond to any requests. 

Best case, if you're stuck here, might be to wait 10-15 minutes and if the robot still isn't available, try to restart and potentially reflash.
