### ISSUE TITLE
Show whether or not a device is running the latest version of Valetudo

### ISSUE THREAD

**Issue by SA0TAY** [Hypfer/valetudo-companion#20]
Currently, you have to dig into the web interface of each device and run the updater to check if there's a new version available. Since the Valetudo companion app can already tell what version devices are running, it strikes me as a trivial yet significant enhancement to compare this version number with whatever the current version is and flag the device in the device list if it's not a match.

**Comment by Hypfer** [comment]
I don't see the point in doing that.

Generally speaking, I really do not want to constantly nudge people to run the latest version of the software, as there is simply no need to do so in the context of the project. Why try to get the user to change something about their setup when they're not actively looking for changes? 

The tasmota docs on upgrading put it best:
https://tasmota.github.io/docs/Upgrading/

> The first rule of upgrading: If it ain't broke, don't fix it!
> In other words, ensure that there is a good reason to mess with a working installation (e.g., a need to use a new feature or address a found problem fixed in the current version).


If such a good reason arises, people will start looking into the software version by themself without any external input, meaning that there is just no need to tell them that they should update. After all they're happy with what they got or else they would've changed something about it.



I'm aware that this _unusual_ in a world where even your toaster will nag you every three days about some absolutely required firmware update, but that's also one of the perks of having a non-commercial local-only software project.

Those two things rule out the most common reasons for pushing people to update:
- As it is not a commercial project, there is no need to forcefully push new tracking nonsense onto the user
- As it is not a commercial project, it is also not required to constantly excite users with new stuff so that they don't get poached by the competition who does just that constant feature bombardment
- As there is no cloud involved, there can't be any cloud API changes that would break the device if not updated.
- As it is local only and not on the internet, there can't be any serious security vulnerabilities that need instant fixing or else someone on the internet will take over the device
